<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Network Map Viewer</AssemblyName>
    <AssemblyTitle>Network Map Viewer</AssemblyTitle>
    <ApplicationIcon>icone.ico</ApplicationIcon>
    <Title>Network Map Viewer </Title>
    <Copyright>Artur Tonoyan</Copyright>
    <PackageIcon>icon.png</PackageIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icone.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Selenium.WebDriver" Version="4.45.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="150.0.7871.11500" />
  </ItemGroup>

</Project>
